PROG GARDEN ST: 车租和保险
TOYOTA: 车租和保险
PUBLIC SERVICE: 水电网费
OPTIMUM: 水电网费
EVERYDAY: 餐饮
PRINCET: 餐饮
PPK CAFÉ: 餐饮
FOOD: 餐饮
PIZZ: 餐饮
BAKERY: 餐饮
CITI AUTOPAY: 娱乐/购物
COSTCO: 娱乐/购物
SHOPRITE: 娱乐/购物
7-ELEVEN: 娱乐/购物
